version: '3'
services:
  myboocontainer: 
    container_name: myboocontainer
    build: .
  nginx: 
    container_name: nginx
    build: .
    ports:
      - "80:80"
    depends_on:
      - wordpress  
    volumes:
    -  /Users/badriah/Desktop/bmount:/var/lib/mysql

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
    -  /Users/badriah/Desktop/bmount:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
    -  /Users/badriah/Desktop/bmount:/var/lib/mysql

# version: '3'
#   web:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./html:/usr/share/nginx/html
#     depends_on:
#       - php
#   php:
#     image: php:7.2-fpm-alpine
#     volumes:
#       - ./html:/var/www/html
# ```