version: '3'
services:
  # myboocontainer: 
  #   container_name: myboocontainer
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  nginx: 
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - wordpress  

  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
    -  /Users/badriah/Desktop/dbmount:/var/lib/mysql

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
    -  /Users/badriah/Desktop/wp:/var/www/html

# version: '3'
#   web:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./html:/usr/share/nginx/html
#     depends_on:
#       - php
#   php:
#     image: php:7.2-fpm-alpine
#     volumes:
#       - ./html:/var/www/html
# ```